---
title: "Causal Modeling in R"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: middle, center, inverse, 

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, tibble.max_extra_cols = 6, tibble.width = 60)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", dpi = 320)
library(tidyverse)
library(gapminder)
```

# **Prediction vs. Explanation**

---
class: middle, center, inverse, 

# Normal regression estimates associations. But we want *causal* estimates: what would happen if *everyone* in the study were exposed to x vs if *no one* was exposed.


---

class: inverse
# Marginal Structural Models
1. Fit a model for the *exposure*, ` x ~ z` where z is all covariates
2. Get the predictions for that model, then invert them
3. Use the inverted probabilities as weights in a second model of `y ~ x`

---

class: inverse
# G-Computation/G-Formula
1. Fit a model for `y ~ x + z` where z is all covariates
2. Create a duplicate of your data set for each level of `x` 
3. Set the value of x to a single value for each cloned data set (e.g `x = 1` for one, `x = 0` for the other)

---

class: inverse
# G-Computation/G-Formula
4. Make predictions using the model on the cloned data sets
5. Get the estimate you want, e.g. `mean(x_1) - mean(x_0)`
---
class: inverse

# Picking variables for the model
1. Build a DAG
2. Choose a reasonable set of variables that blocks all other associations between x and y that are not causal

---
class: inverse, center, middle

# **Work your way through `exercises.Rmd`**

---

class: inverse, center

# Resources
## [Causal Inference](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/): *The* book on causal inference. Free online.
## [Causal Inference Notebook](http://causalinferencebookr.netlify.com): R code to go along with Causal Inference
