---
title: "Dynamic documents in R"
subtitle: "Making figures in R Markdown"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "theme.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: false
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE, tibble.max_extra_cols = 6, tibble.width = 60)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", dpi = 320)
library(tidyverse)
library(gapminder)
library(here)
diabetes <- read_csv("diabetes.csv")
```


---

```{r, fig.width=5.5, eval=FALSE}
library(ggdag, warn.conflicts = FALSE)
ggdag(butterfly_bias()) + 
  theme_dag() + 
  scale_x_continuous(expand = expansion(.3)) +  #<<
  scale_y_continuous(expand = expansion(.3)) #<<
```

---

```{r, fig.width=5.5, echo=FALSE}
library(ggdag, warn.conflicts = FALSE)
ggdag(butterfly_bias()) + 
  theme_dag() + 
  scale_x_continuous(expand = expansion(.3)) +  #<<
  scale_y_continuous(expand = expansion(.3)) #<<
```
---

class: inverse, center

# Resources
## [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/): Includes various recipes for figures
## [Jumping Rivers Blog Series](https://www.jumpingrivers.com/blog/knitr-rmarkdown-image-size/): A blog series on images in R Markdown
## [Taking Control of Plot Scaling](https://www.tidyverse.org/blog/2020/08/taking-control-of-plot-scaling): A detailed blog on understanding scaling
