---
title: "R Markdown: Whole Game"
output: html_document
---

```{r setup}
library(tidyverse)
```

For this set of exercises, we'll work through an R Markdown report in `whole_game.Rmd`.
Open up that file and follow along with these exercises:

## Your Turn 1

1.  Turn on Visual R Markdown mode for `exercises.Rmd` (this document) AND `whole_game.Rmd`
2.  In your local R session, run the code in the code chunk called "prep-data". Look at the chunk options (everything after "r prep-data". What do you think setting the `include` option does?
3.  Knit the document and take a look. Were you right?

## Your Turn 2

1.  Add a citation to the methods section for the data. Use the citation wizard to search PubMed for an article called "Prevalence of coronary heart disease risk factors among rural blacks: A community-based study"

## Your Turn 3

1.  Take a look at the chunk called "descriptive-stats." What do you think `echo = FALSE` does, and how is it different from `include = FALSE`? What do you think `eval = FALSE` means?
2.  Read the code in "descriptive-stats". What are we preparing?
3.  Look at the narrative text right after "descriptive-stats". It's full of bits of code. What are we doing here, and what do you think the output should look like?
4.  Change `eval` to `TRUE` in the "descriptive-stats" code chunk and re-knit. Look at this part of the document. What does the output look like?

## Your Turn 4

1.  In the code chunk called "table-one", create a descriptive table with `tbl_summary()`
2.  Pipe the results of `tbl_summary()` to `add_difference()`.
3.  Change `eval` to `TRUE` and re-knit

## Your Turn 5

1.  In the code chunk called "figure-one", load the patchwork library

2.  At the end of the code chunk, include this code: `fig1a + fig1b` .
    patchwork allows you to join ggplots with `+` (and more).

3.  At the top of the document, change `output: html_document` to this code (be mindful to keep the indents as is):

    ``` {.yaml}
    output: 
      bookdown::html_document2:
        number_sections: false
    ```

4.  In "figure-one", add a chunk option: `fig.cap = "A1c and diabetes status by WH ratio"` .
    Then, where it says "Figure \_\_\_\_\_", add \@ref(fig:figure-one)

5.  In "figure-one", change `eval` to `TRUE` and re-knit

## Your Turn 6

1.  In the code chunk called "table-two", pass the results of both `lm()` and `glm()` to `tbl_regression()`
2.  Merge the two model tables using `tbl_merge()`
3.  change `eval` to `TRUE` and re-knit

**Stretch goal**: The description for Table 2 is pretty sparse.
It would probably be better to have some numbers included in the narrative text.
Read gtsummary's [vignette on inline text](http://www.danieldsjoberg.com/gtsummary/articles/inline_text.html) and add a few important details.

## Your Turn 7

Previously, we only had data for one location in the study---Buckingham.
We've just received data from the other site, Louisa, and we need to update the tables, figures, and narrative text...

...but since we used R Markdown, we can just load the new data set, and R will update everything for us.

1.  Change `read_csv()` to load `diabetes.csv` instead of `diabetes-buckingham.csv`
2.  Add the `location` variable to Table 1
3.  Re-knit. How's it look?
