---
title: "Designing ggplots"
output: html_document
---

```{r setup}
library(tidyverse)
```

## Your Turn

```{r}
emperors <- read_csv("data/emperors.csv")

emperors |>
  mutate(killer = fct_lump(killer, 10)) |>
  count(killer) |>
  arrange(n) |>
  mutate(
    lightning = ifelse(killer == "Lightning", TRUE, FALSE),
    killer = fct_inorder(killer)
  ) |>
  ggplot(aes(x = n, y = killer, fill = lightning)) +
  geom_col() +
  geom_text(aes(label = n, x = n - .25), color = "white", size = 6, hjust = 1) +
  cowplot::theme_minimal_vgrid(16) +
  theme(
    axis.title.y = element_blank(), 
    legend.position = "none" 
  ) +
  scale_fill_manual(name = NULL, values = c("#B0B0B0D0", "#BD3828D0")) +
  xlab("number of emperors")
```


## Your Turn 

```{r}
library(gapminder)
library(ggrepel)

sample_countries <- function(x) {
  x |>
    sample_n(10)
}

set.seed(541)

countries <- gapminder |>
  sample_countries() |>
  pull(country)


gapminder |>
  filter(year == 2007) |>
  mutate(
    label = ifelse(country %in% countries, as.character(country), "")
  ) |>
  ggplot(aes(log(gdpPercap), lifeExp)) +
  geom_point(size = 3.5, alpha = .9, shape = 21, col = "white", fill = "#0162B2") +
  geom_text_repel(
    aes(label = label), 
    size = 4.5,
    point.padding = .2, 
    box.padding = .3, 
    force = 1,
    min.segment.length = 0
  ) +
  theme_minimal(14) +
  theme(
    legend.position = "none",
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  labs(
    x = "log(GDP per capita)",
    y = "life expectancy"
  )
```


## Your Turn 

```{r}
library(cowplot)

continent_data <- gapminder |>
  group_by(continent, year) |>
  summarise(lifeExp = mean(lifeExp))

direct_labels <- continent_data |>
  group_by(continent) |>
  summarize(x = max(year), y = max(lifeExp))

p <- continent_data |>
  ggplot(aes(year, lifeExp, col = continent)) +
  geom_line(size = 1) +
  theme_minimal_hgrid() +
  theme(legend.position = "none") +
  scale_color_manual(values = continent_colors) +
  scale_x_continuous(expand = expansion()) +
  labs(y = "life expectancy")

direct_labels_axis <- axis_canvas(p, axis = "y") +
  geom_text(
    data = direct_labels, 
    aes(y = y, label = continent),
    x = 0.05, 
    hjust = 0,
    size = 4.5
  )

p_direct_labels <- insert_yaxis_grob(p, direct_labels_axis)

ggdraw(p_direct_labels)
```


## Your Turn


```{r}
library(gghighlight)
africa <- gapminder |>
  filter(continent == "Africa")

# find the African countries that had better life expectancy in 1992 compared to 2007
life_expectancy_dropped <- africa |>
  pivot_wider(country, names_from = year, values_from = lifeExp) |>
  transmute(country, le_dropped = `1992` > `2007`)

africa |> 
  # join `le_dropped` to each observation for each country
  left_join(life_expectancy_dropped, by = "country") |>
  ggplot(aes(year, lifeExp, col = country)) +
  geom_line(size = 1.2, alpha = .9, col = "#E58C23") +
  gghighlight(le_dropped, use_group_by = FALSE, use_direct_label = FALSE, unhighlighted_colour = "grey90") +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  labs(y = "life expectancy") +
  xlim(1950, 2015) +
  facet_wrap(~country)
```


## Your Turn

```{r}
diabetes <- read_csv("data/diabetes.csv")

density_colors <- c(
  "male" = "#56B4E9",
  "female" = "#009E73",
  "all participants" = "grey85"
)

diabetes |>
  drop_na(glyhb, gender) |> 
  ggplot(aes(glyhb)) +
  geom_density(aes(fill = gender, color = gender)) +
  scale_x_log10(name = "glycosylated hemoglobin a1c") +
  scale_color_manual(name = NULL, values = density_colors) +
  scale_fill_manual(name = NULL, values = density_colors) +
  theme_minimal_hgrid(16) +
  theme(legend.position = "bottom", legend.justification = "center")
```


```{r}
diabetes |>
  drop_na(glyhb, gender) |> 
  ggplot(aes(glyhb, y = ..count..)) +
  geom_density(data = function(x) select(x, glyhb), aes(fill = "all participants", color = "all participants")) +
  geom_density(aes(fill = gender, color = gender)) +
  scale_x_log10(name = "glycosylated hemoglobin a1c") +
  scale_color_manual(name = NULL, values = density_colors) +
  scale_fill_manual(name = NULL, values = density_colors) +
  facet_wrap(vars(gender)) +
  theme_minimal_hgrid(16) +
  theme(legend.position = "bottom", legend.justification = "center")
```


## Your Turn

```{r}
la_heat_income <- sf::read_sf("data/los-angeles.geojson")
kelvin2farenheit <- function(k) (9/5) * (k - 273) + 32

la_heat_income |>
  mutate(temp = kelvin2farenheit(X_median)) |>
  ggplot() +
  geom_sf(aes(fill = temp), color = "white", size = .2) +
  cowplot::theme_map() +
  theme(legend.position = c(.9, .2)) +
  scale_fill_viridis_c(option = "inferno") +
  coord_sf(clip = "off") # don't clip text that runs off the main plotting panel
```


```{r}
# adding line breaks here will automatically add `\n` to the text, which will insert a linebreak when printed
# or you can add them yourself or use a function like `str_wrap()`
left_label <- "The coolest corridor, from Santa Monica
to Griffith Park, was also the richest,
with higher median household income
than the rest of Los Angeles"

right_label <- "Census tracts in the north and southeast
of Los Angeles were its hottest. Like a lot
of US cities, these are also the places
nwhere its poorest residents live."

annotations <- tibble::tribble(
  ~x,      ~y,    ~label,
  -118.90, 34.00, left_label,
  -118.20, 34.22, right_label
)

curves <- tibble::tribble(
  ~x,      ~y,    ~xend,    ~yend,
  -118.73, 34.035, -118.60, 34.10, # west side, pointing northeast
  -118.21, 34.195, -118.35, 34.18, # northeast, pointing northwest
  -118.08, 34.185, -118.15, 34.10  # northeast, pointing southwest
)


la_heat_income |>
  mutate(temp = kelvin2farenheit(X_median)) |>
  ggplot() +
  geom_sf(aes(fill = temp), color = "white", size = .2) +
  geom_text(
    data = annotations,
    aes(x, y, label = label),
    hjust = 0,
    vjust = 0.5,
    lineheight = 0.8
  ) + geom_curve(
    data = curves,
    aes(x =x, y = y, xend = xend, yend = yend),
    colour = "grey75",
    size = 0.3,
    curvature = -0.1,
    arrow = arrow(length = unit(0.01, "npc"), type = "closed")
  ) +
  coord_sf(clip = "off") + # don't clip text that runs off the main plotting panel
  cowplot::theme_map() +
  theme(legend.position = c(.9, .2)) +
  scale_fill_viridis_c(name = "temperature (F°)", option = "inferno")

```


## Your Turn

```{r}
label_frames <- function(lbl) paste(lbl, "\nframe")

theme_multiplot <- function(base_size = 14, ...) {
  theme_minimal(base_size = base_size, ...) %+replace%
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      legend.position = "none"
    )
}

diabetes_complete <- diabetes |> 
  drop_na(waist, hip, gender, frame, glyhb)
```


```{r}
plot_a <- diabetes_complete |> 
  ggplot(aes(waist/hip, fill = gender)) + 
    geom_density(
      col = "white", 
      alpha = .7, 
      size = .75
     ) + 
    theme_multiplot() +
    scale_fill_manual(values = c("#009E73", "#0072B2")) + 
    annotate(
       "text", 
       x = c(.75, .98), 
       y = c(5, 5.70), 
       label = c("female", "male"), 
       color = c("#009E73", "#0072B2"),
       size = 5
      ) + 
    labs(tag = "A") 

plot_a
```


```{r}
plot_b <- diabetes_complete |> 
  ggplot(aes(fct_rev(frame), waist/hip, fill = gender, col = gender)) + 
    geom_boxplot(
      outlier.color = NA, 
      alpha = .8, 
      width = .5
     ) +
    theme_multiplot() +
    theme(axis.title.x = element_blank()) + 
    scale_x_discrete(labels = label_frames) + 
    scale_color_manual(values = c("#009E73", "#0072B2")) + 
    scale_fill_manual(values = c("#009E7370", "#0072B270")) + 
    labs(tag = "B")

plot_b
```


```{r}
plot_c <- diabetes_complete |> 
  ggplot(aes(waist/hip, glyhb,  col = gender)) +
    geom_point(
      shape = 21, 
      col = "white", 
      fill = "grey80", 
      size = 2.5
     ) + 
    geom_smooth(
      method = "lm", 
      formula = y ~ x,
      se = FALSE, 
      size = 1.3
    ) + 
    theme_minimal(base_size = 14) +
    theme(
      legend.position = c(1, 1.25),
      legend.justification = c(1, 0),
      legend.direction = "horizontal",
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank()
     ) + 
    facet_wrap(~fct_rev(frame), labeller = as_labeller(label_frames)) +
    labs(tag = "C", y = "hemoglobin a1c") + 
    scale_y_log10(breaks = c(3.5, 5.0, 7.0, 10.0, 14.0)) +
    scale_color_manual(name = "", values = c("#009E73FF", "#0072B2FF")) +
    guides(color = guide_legend(override.aes = list(size = 5)))
    
plot_c
```


```{r}
library(patchwork)
(plot_a + plot_b) / plot_c
```



***

# Take aways

